<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LEIs-MacBook-Pro.local" failures="2" tests="9" name="RetryMultipleFailedTestCases" time="0.065" errors="0" timestamp="11 Jun 2020 23:58:23 GMT">
  <testcase classname="mytest.MyTests" name="test1" time="0.012">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="mytest.MyTests" name="test1" time="0.002">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="mytest.MyTests" name="test1" time="0.004">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="mytest.MyTests" name="test1" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at mytest.MyTests.test1(MyTests.java:11)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="mytest.MyTests" name="test2" time="0.003">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="mytest.MyTests" name="test2" time="0.001">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="mytest.MyTests" name="test2" time="0.002">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="mytest.MyTests" name="test2" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at mytest.MyTests.test2(MyTests.java:16)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="mytest.MyTests" name="test3" time="0.001"/>
</testsuite> <!-- RetryMultipleFailedTestCases -->
